import { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    price: 79.99,
    originalPrice: 99.99,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500&h=500&fit=crop",
    ],
    category: "Electronics",
    description: "Premium wireless Bluetooth headphones with noise cancellation and 30-hour battery life. Perfect for music lovers and professionals.",
    shortDescription: "Premium wireless headphones with noise cancellation",
    inStock: true,
    rating: 4.5,
    reviewCount: 234,
    variants: {
      color: ["Black", "White", "Blue"],
    },
    tags: ["wireless", "bluetooth", "audio"],
  },
  {
    id: "2",
    name: "Smart Watch Pro",
    price: 299.99,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop",
    category: "Electronics",
    description: "Advanced smartwatch with fitness tracking, heart rate monitor, GPS, and smartphone notifications. Water-resistant design.",
    shortDescription: "Advanced smartwatch with fitness tracking",
    inStock: true,
    rating: 4.7,
    reviewCount: 189,
    variants: {
      size: ["40mm", "44mm"],
      color: ["Black", "Silver", "Rose Gold"],
    },
    tags: ["smartwatch", "fitness", "wearable"],
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    price: 29.99,
    originalPrice: 39.99,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop",
    category: "Clothing",
    description: "Comfortable organic cotton t-shirt in various colors. Sustainable and eco-friendly material.",
    shortDescription: "Comfortable organic cotton t-shirt",
    inStock: true,
    rating: 4.3,
    reviewCount: 156,
    variants: {
      size: ["S", "M", "L", "XL"],
      color: ["White", "Black", "Navy", "Gray"],
    },
    tags: ["organic", "cotton", "sustainable"],
  },
  {
    id: "4",
    name: "Leather Backpack",
    price: 149.99,
    image: "https://picsum.photos/500/500?random=4",
    category: "Accessories",
    description: "Stylish leather backpack with multiple compartments. Perfect for work, travel, or daily use.",
    shortDescription: "Stylish leather backpack",
    inStock: true,
    rating: 4.6,
    reviewCount: 98,
    variants: {
      color: ["Brown", "Black"],
    },
    tags: ["leather", "backpack", "travel"],
  },
  {
    id: "5",
    name: "Wireless Mouse",
    price: 24.99,
    image: "https://picsum.photos/500/500?random=5",
    category: "Electronics",
    description: "Ergonomic wireless mouse with precision tracking and long battery life.",
    shortDescription: "Ergonomic wireless mouse",
    inStock: true,
    rating: 4.4,
    reviewCount: 312,
    variants: {
      color: ["Black", "White"],
    },
    tags: ["mouse", "wireless", "computer"],
  },
  {
    id: "6",
    name: "Running Shoes",
    price: 89.99,
    originalPrice: 119.99,
    image: "https://picsum.photos/500/500?random=6",
    category: "Footwear",
    description: "Lightweight running shoes with cushioned sole and breathable mesh upper.",
    shortDescription: "Lightweight running shoes",
    inStock: true,
    rating: 4.5,
    reviewCount: 267,
    variants: {
      size: ["7", "8", "9", "10", "11", "12"],
      color: ["Black", "White", "Blue"],
    },
    tags: ["running", "shoes", "sports"],
  },
  {
    id: "7",
    name: "Coffee Maker",
    price: 59.99,
    image: "https://picsum.photos/500/500?random=7",
    category: "Home",
    description: "Programmable coffee maker with thermal carafe. Makes up to 12 cups.",
    shortDescription: "Programmable coffee maker",
    inStock: true,
    rating: 4.2,
    reviewCount: 145,
    variants: {
      color: ["Black", "White", "Stainless Steel"],
    },
    tags: ["coffee", "kitchen", "appliance"],
  },
  {
    id: "8",
    name: "Yoga Mat",
    price: 34.99,
    image: "https://picsum.photos/500/500?random=8",
    category: "Sports",
    description: "Non-slip yoga mat with carrying strap. Extra thick for comfort.",
    shortDescription: "Non-slip yoga mat",
    inStock: true,
    rating: 4.6,
    reviewCount: 203,
    variants: {
      color: ["Purple", "Blue", "Pink", "Gray"],
    },
    tags: ["yoga", "fitness", "exercise"],
  },
  {
    id: "9",
    name: "Laptop Stand",
    price: 49.99,
    image: "https://picsum.photos/500/500?random=9",
    category: "Electronics",
    description: "Adjustable aluminum laptop stand for better ergonomics and cooling.",
    shortDescription: "Adjustable laptop stand",
    inStock: true,
    rating: 4.4,
    reviewCount: 178,
    variants: {
      color: ["Silver", "Space Gray"],
    },
    tags: ["laptop", "stand", "ergonomic"],
  },
  {
    id: "10",
    name: "Water Bottle",
    price: 19.99,
    image: "https://picsum.photos/500/500?random=10",
    category: "Accessories",
    description: "Stainless steel insulated water bottle. Keeps drinks cold for 24 hours.",
    shortDescription: "Insulated water bottle",
    inStock: true,
    rating: 4.7,
    reviewCount: 289,
    variants: {
      color: ["Black", "White", "Blue", "Pink"],
      size: ["500ml", "750ml", "1L"],
    },
    tags: ["water", "bottle", "insulated"],
  },
  {
    id: "11",
    name: "Desk Lamp",
    price: 39.99,
    image: "https://picsum.photos/500/500?random=11",
    category: "Home",
    description: "LED desk lamp with adjustable brightness and color temperature.",
    shortDescription: "LED desk lamp",
    inStock: true,
    rating: 4.3,
    reviewCount: 134,
    variants: {
      color: ["Black", "White"],
    },
    tags: ["lamp", "desk", "LED"],
  },
  {
    id: "12",
    name: "Phone Case",
    price: 24.99,
    image: "https://picsum.photos/500/500?random=12",
    category: "Accessories",
    description: "Protective phone case with shock absorption and raised edges.",
    shortDescription: "Protective phone case",
    inStock: true,
    rating: 4.5,
    reviewCount: 456,
    variants: {
      color: ["Clear", "Black", "Blue", "Red"],
    },
    tags: ["phone", "case", "protection"],
  },
  {
    id: "13",
    name: "Sunglasses",
    price: 79.99,
    originalPrice: 129.99,
    image: "https://picsum.photos/500/500?random=13",
    category: "Accessories",
    description: "Polarized sunglasses with UV protection and scratch-resistant lenses.",
    shortDescription: "Polarized sunglasses",
    inStock: true,
    rating: 4.6,
    reviewCount: 167,
    variants: {
      color: ["Black", "Brown", "Gray"],
    },
    tags: ["sunglasses", "eyewear", "UV protection"],
  },
  {
    id: "14",
    name: "Bluetooth Speaker",
    price: 69.99,
    image: "https://picsum.photos/500/500?random=14",
    category: "Electronics",
    description: "Portable Bluetooth speaker with 360-degree sound and waterproof design.",
    shortDescription: "Portable Bluetooth speaker",
    inStock: true,
    rating: 4.4,
    reviewCount: 223,
    variants: {
      color: ["Black", "Blue", "Red"],
    },
    tags: ["speaker", "bluetooth", "portable"],
  },
  {
    id: "15",
    name: "Gaming Keyboard",
    price: 89.99,
    image: "https://picsum.photos/500/500?random=15",
    category: "Electronics",
    description: "Mechanical gaming keyboard with RGB backlighting and programmable keys.",
    shortDescription: "Mechanical gaming keyboard",
    inStock: true,
    rating: 4.7,
    reviewCount: 312,
    variants: {
      color: ["Black", "White"],
    },
    tags: ["keyboard", "gaming", "mechanical"],
  },
  {
    id: "16",
    name: "Fitness Tracker",
    price: 49.99,
    image: "https://picsum.photos/500/500?random=16",
    category: "Electronics",
    description: "Activity tracker with heart rate monitor, sleep tracking, and smartphone sync.",
    shortDescription: "Activity tracker",
    inStock: true,
    rating: 4.3,
    reviewCount: 198,
    variants: {
      color: ["Black", "Pink", "Blue"],
    },
    tags: ["fitness", "tracker", "health"],
  },
  {
    id: "17",
    name: "Tablet Stand",
    price: 29.99,
    image: "https://picsum.photos/500/500?random=17",
    category: "Electronics",
    description: "Adjustable tablet stand for comfortable viewing and typing.",
    shortDescription: "Adjustable tablet stand",
    inStock: true,
    rating: 4.2,
    reviewCount: 87,
    variants: {
      color: ["Black", "Silver"],
    },
    tags: ["tablet", "stand", "accessory"],
  },
  {
    id: "18",
    name: "Wireless Charger",
    price: 19.99,
    image: "https://picsum.photos/500/500?random=18",
    category: "Electronics",
    description: "Fast wireless charging pad compatible with Qi-enabled devices.",
    shortDescription: "Wireless charging pad",
    inStock: true,
    rating: 4.5,
    reviewCount: 267,
    variants: {
      color: ["Black", "White"],
    },
    tags: ["charger", "wireless", "Qi"],
  },
  {
    id: "19",
    name: "Hoodie",
    price: 49.99,
    image: "https://picsum.photos/500/500?random=19",
    category: "Clothing",
    description: "Comfortable cotton hoodie with front pocket and drawstring hood.",
    shortDescription: "Comfortable cotton hoodie",
    inStock: true,
    rating: 4.4,
    reviewCount: 189,
    variants: {
      size: ["S", "M", "L", "XL", "XXL"],
      color: ["Black", "Gray", "Navy", "Red"],
    },
    tags: ["hoodie", "clothing", "casual"],
  },
  {
    id: "20",
    name: "Backpack",
    price: 59.99,
    image: "https://picsum.photos/500/500?random=20",
    category: "Accessories",
    description: "Durable backpack with laptop compartment and multiple pockets.",
    shortDescription: "Durable backpack",
    inStock: true,
    rating: 4.5,
    reviewCount: 234,
    variants: {
      color: ["Black", "Gray", "Blue"],
    },
    tags: ["backpack", "bag", "travel"],
  },
  {
    id: "21",
    name: "Desk Organizer",
    price: 24.99,
    image: "https://picsum.photos/500/500?random=21",
    category: "Home",
    description: "Bamboo desk organizer with multiple compartments for office supplies.",
    shortDescription: "Bamboo desk organizer",
    inStock: true,
    rating: 4.3,
    reviewCount: 112,
    variants: {
      color: ["Natural", "Dark"],
    },
    tags: ["organizer", "desk", "office"],
  },
  {
    id: "22",
    name: "Power Bank",
    price: 34.99,
    image: "https://picsum.photos/500/500?random=22",
    category: "Electronics",
    description: "High-capacity power bank with fast charging and multiple ports.",
    shortDescription: "High-capacity power bank",
    inStock: true,
    rating: 4.6,
    reviewCount: 298,
    variants: {
      color: ["Black", "White", "Blue"],
      size: ["10000mAh", "20000mAh"],
    },
    tags: ["power bank", "charger", "portable"],
  },
  {
    id: "23",
    name: "Jeans",
    price: 69.99,
    originalPrice: 89.99,
    image: "https://picsum.photos/500/500?random=23",
    category: "Clothing",
    description: "Classic fit jeans with stretch for comfort and durability.",
    shortDescription: "Classic fit jeans",
    inStock: true,
    rating: 4.4,
    reviewCount: 345,
    variants: {
      size: ["28", "30", "32", "34", "36", "38"],
      color: ["Blue", "Black", "Gray"],
    },
    tags: ["jeans", "clothing", "denim"],
  },
  {
    id: "24",
    name: "Monitor Stand",
    price: 44.99,
    image: "https://picsum.photos/500/500?random=24",
    category: "Electronics",
    description: "Ergonomic monitor stand with storage space underneath.",
    shortDescription: "Ergonomic monitor stand",
    inStock: true,
    rating: 4.3,
    reviewCount: 156,
    variants: {
      color: ["Black", "White"],
    },
    tags: ["monitor", "stand", "desk"],
  },
  {
    id: "25",
    name: "Sneakers",
    price: 79.99,
    image: "https://picsum.photos/500/500?random=25",
    category: "Footwear",
    description: "Comfortable sneakers with cushioned sole and breathable upper.",
    shortDescription: "Comfortable sneakers",
    inStock: true,
    rating: 4.5,
    reviewCount: 278,
    variants: {
      size: ["7", "8", "9", "10", "11", "12"],
      color: ["White", "Black", "Gray"],
    },
    tags: ["sneakers", "shoes", "casual"],
  },
]

export const categories = [
  "All",
  "Electronics",
  "Clothing",
  "Accessories",
  "Footwear",
  "Home",
  "Sports",
]

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "All") return products
  return products.filter((p) => p.category === category)
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowerQuery) ||
      p.description.toLowerCase().includes(lowerQuery) ||
      p.category.toLowerCase().includes(lowerQuery) ||
      p.tags?.some((tag) => tag.toLowerCase().includes(lowerQuery))
  )
}
